# Generated by Django 5.0 on 2024-01-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eccomapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_number',
        ),
    ]
