# Generated by Django 5.0 on 2024-01-03 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccomapp', '0002_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catogories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catogory_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_product', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('catogories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eccomapp.catogories')),
            ],
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
