# Generated by Django 5.0 on 2024-01-25 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember1',
            name='categories',
        ),
        migrations.AddField(
            model_name='usermember1',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceapp.categories'),
        ),
    ]
