# Generated by Django 5.0 on 2024-01-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_remove_usermember1_categories_usermember1_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember1',
            name='category',
        ),
        migrations.AddField(
            model_name='usermember1',
            name='categories',
            field=models.ManyToManyField(null=True, to='serviceapp.categories'),
        ),
    ]
