# Generated by Django 5.0 on 2024-01-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_remove_usermember1_category_usermember1_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember1',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='members', to='serviceapp.categories'),
        ),
    ]
