# Generated by Django 5.0 on 2024-01-26 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_alter_usermember1_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember1',
            name='new_dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.categories'),
        ),
    ]
