# Generated by Django 5.0 on 2024-01-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0005_alter_usermember1_new_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember1',
            name='new_dept',
        ),
        migrations.RemoveField(
            model_name='usermember1',
            name='categories',
        ),
        migrations.AddField(
            model_name='usermember1',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.categories'),
        ),
    ]
