# Generated by Django 5.0 on 2024-01-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0006_remove_usermember1_new_dept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember1',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Rejected')], default='1', max_length=1),
        ),
    ]
