# Generated by Django 5.0 on 2024-01-31 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0009_usermember1_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='usermember1',
            name='created_by',
        ),
    ]
