# Generated by Django 5.0 on 2024-02-12 07:22

import serviceapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0013_service_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=serviceapp.models.DurationField(max_length=20, null=True),
        ),
    ]
