# Generated by Django 5.0 on 2024-02-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0014_alter_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='created_by_type',
            field=models.CharField(default='1', max_length=10, null=True),
        ),
    ]
