# Generated by Django 5.0 on 2024-02-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0020_booking_user1_alter_booking_date_of_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user1',
        ),
    ]
