# Generated by Django 5.0 on 2024-02-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0021_remove_booking_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='status',
            field=models.CharField(default='1', max_length=1, null=True),
        ),
    ]
