# Generated by Django 5.0 on 2024-02-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0022_usermember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='task_compleated',
            field=models.CharField(default='1', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='worker_approval',
            field=models.CharField(default='1', max_length=3, null=True),
        ),
    ]
