# Generated by Django 5.0 on 2024-02-29 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0023_booking_task_compleated_booking_worker_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.usermember')),
            ],
        ),
    ]
