# Generated by Django 5.0 on 2024-02-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0024_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
