# Generated by Django 5.0 on 2024-03-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0027_booking_added_by_review_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='added_by',
        ),
    ]
