# Generated by Django 5.0 on 2024-03-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0034_alter_review_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
    ]
