# Generated by Django 5.0 on 2024-03-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0036_review_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='service',
            new_name='bookings',
        ),
       
    ]
