# Generated by Django 5.0 on 2024-03-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0037_rename_service_review_bookings_remove_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
