# Generated by Django 5.0 on 2024-03-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0039_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
