# Generated by Django 5.0 on 2024-03-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0040_remove_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='created_by',
        ),
    ]
