# Generated by Django 5.0 on 2024-04-01 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0042_categories_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_member1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.usermember1'),
        ),
    ]
