# Generated by Django 5.0 on 2024-04-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0043_booking_user_member1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_member1',
        ),
    ]
