# Generated by Django 5.0 on 2024-04-01 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0044_remove_booking_user_member1'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
