# Generated by Django 5.0 on 2023-12-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_adress',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_address',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.IntegerField(null=True),
        ),
    ]
