# Generated by Django 5.0 on 2023-12-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForeignkeyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_adress',
            new_name='student_address',
        ),
    ]
