# Generated by Django 5.0 on 2024-01-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember1',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
