# Generated by Django 5.0 on 2024-01-16 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_alter_usermember1_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember1',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermember1_categories', to='sampleapp.categories'),
        ),
        migrations.AlterField(
            model_name='usermember1',
            name='new_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermember1_new_dept', to='sampleapp.categories'),
        ),
    ]
