# Generated by Django 5.0 on 2024-01-18 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_alter_usermember1_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember1',
            name='confirmation_code',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        # ... other operations ...
    ]
