# Generated by Django 5.0 on 2024-01-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0005_usermember1_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember1',
            name='confirmation_code',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
