# Generated by Django 5.0 on 2024-01-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0007_usermember_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember1',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
