# Generated by Django 5.0 on 2024-01-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0008_alter_usermember1_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember1',
            name='autogenerated_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usermember1',
            name='autogenerated_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermember1',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
