# Generated by Django 5.0 on 2024-01-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0009_usermember1_autogenerated_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember1',
            name='confirmation_code',
        ),
    ]
