# Generated by Django 5.0 on 2024-01-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0010_remove_usermember1_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember1',
            name='autogenerated_password',
        ),
        migrations.RemoveField(
            model_name='usermember1',
            name='autogenerated_username',
        ),
        migrations.AddField(
            model_name='usermember1',
            name='registration_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='usermember1',
            name='is_approved',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
