# Generated by Django 5.0 on 2024-01-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0011_remove_usermember1_autogenerated_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='c_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
