# Generated by Django 5.0 on 2024-01-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0012_customuser_is_worker_alter_usermember_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'User'), (3, 'Worker')], default=1),
        ),
    ]
