# Generated by Django 5.0 on 2024-01-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember1',
            name='autogenerated_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usermember1',
            name='autogenerated_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
