# Generated by Django 5.0 on 2024-01-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0014_usermember1_autogenerated_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember1',
            name='autogenerated_password',
        ),
        migrations.RemoveField(
            model_name='usermember1',
            name='autogenerated_username',
        ),
    ]
