# Generated by Django 5.0 on 2024-01-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0015_remove_usermember1_autogenerated_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_worker',
        ),
        migrations.RemoveField(
            model_name='usermember1',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='usermember1',
            name='registration_status',
        ),
        migrations.AddField(
            model_name='usermember1',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
