# Generated by Django 5.0 on 2024-01-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0016_remove_customuser_is_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default=1, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usermember1',
            name='a_ddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermember1',
            name='contactnumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermember1',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermember1',
            name='experience',
            field=models.CharField(default=1, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='usermember1',
            name='id_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermember1',
            name='status',
            field=models.CharField(default='pending', max_length=10, null=True),
        ),
    ]
