# Generated by Django 5.0 on 2023-12-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField()),
                ('age', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('joiningDate', models.DateField()),
                ('qualification', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=25)),
            ],
        ),
    ]
